version: "3.8"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'jon'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "5432:5432"
    volumes:
      - db:$PWD/volumes
volumes:
  db:
    driver: local

